on: [pull_request]

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -  run: |
        docker image prune -a -f
        docker pull quay.io/eclipse/che-theia-dev:next
        docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
        ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
    - run: |
        docker tag eclipse/che-theia:next ghcr.io/${{ github.repository }}:che-theia--sha-${{ github.event.pull_request.head.sha }}
        docker push ghcr.io/${{ github.repository }}:sha-${{ github.event.pull_request.head.sha }}
    - run: |
        docker tag eclipse/che-theia-endpoint-runtime-binary:next ghcr.io/${{ github.repository }}:che-theia-endpoint-runtime-binary--sha-${{ github.event.pull_request.head.sha }}
        docker push ghcr.io/${{ github.repository }}:sha-${{ github.event.pull_request.head.sha }}
